theme: jekyll-theme-minimal
title: Minh Khanh Thi Dinh | Portfolio
description: Bookmark this to keep an eye on my project updates!
url: https://khanhmdinh.me
baseurl: ""

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

collections:
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope: { path: "", type: "projects" }
    values:
      layout: single
      classes: wide
  - scope: { path: "" }
    values:
      author_profile: false
      toc: false
      read_time: false
      related: false
